### ISSUE TITLE
Can't run with unity editor.

### ISSUE THREAD

**Issue by pilacst** [chemistry-lab/chemistry-lab-vr#76]
I am using Unity 2019.2.12f1 (64-bit) and when I pay the project I could not see the VR app. I have followed the steps given in the readme. Can you support me to resolve this?

The output I can see is following 

![image](https://user-images.githubusercontent.com/3081080/137193127-33877736-4f19-490b-af24-67963937a871.png)

**Comment by drokii** [comment]
We cannot.
